import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import {
  detectImport,
  resolveImport,
  parseSeedText,
  seedFromPlainPem,
  seedFromEncryptedPem,
  seedToHex,
} from "../lib/import";
import { encryptIdentity, decryptIdentity } from "../lib/identity";
import { generateSeed, publicKeyFromSeed } from "../lib/crypto";
import { didFromPublicKey } from "../lib/didkey";

const SEED_HEX = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
const EXPECTED_DID = "did:key:z6MktwupdmLXVVqTzCw4i46r4uGyosGXRnR3XjN4Zq7oMMsw";
const ENC_PEM = "C:/Users/Nur/AppData/Local/Temp/opencode/key-enc.pem";
const PLAIN_PEM = "C:/Users/Nur/AppData/Local/Temp/opencode/key-plain.pem";
const ENC_PASS = "test-passphrase-123";

describe("detectImport", () => {
  it("detects floptools encrypted JSON", async () => {
    const seed = generateSeed();
    const pub = publicKeyFromSeed(seed);
    const file = await encryptIdentity(seed, didFromPublicKey(pub), pub, "correct horse battery staple");
    const det = detectImport(JSON.stringify(file));
    expect(det.kind).toBe("floptools-encrypted");
    expect(det.needsPassphrase).toBe(true);
  });

  it("detects encrypted and plain PEM", () => {
    if (!existsSync(ENC_PEM)) throw new Error("fixture missing: run generate-import-fixtures");
    const enc = readFileSync(ENC_PEM, "utf8");
    const plain = readFileSync(PLAIN_PEM, "utf8");
    expect(detectImport(enc).kind).toBe("pem-encrypted");
    expect(detectImport(plain).kind).toBe("pem-plain");
  });

  it("detects seed JSON and raw seed", () => {
    const det = detectImport(JSON.stringify({ seed: SEED_HEX }));
    expect(det.kind).toBe("seed-json");
    expect(det.did).toBe(EXPECTED_DID);
    const raw = detectImport(SEED_HEX);
    expect(raw.kind).toBe("seed-raw");
    expect(raw.did).toBe(EXPECTED_DID);
  });

  it("reports unknown for garbage", () => {
    expect(detectImport("hello world").kind).toBe("unknown");
    expect(detectImport('{"foo": 1}').kind).toBe("unknown");
    expect(detectImport("-----BEGIN EC PRIVATE KEY-----").kind).toBe("unknown");
  });
});

describe("parseSeedText", () => {
  it("parses 64-char hex", () => {
    const s = parseSeedText(SEED_HEX)!;
    expect(seedToHex(s)).toBe(SEED_HEX);
  });
  it("rejects wrong lengths", () => {
    expect(parseSeedText(SEED_HEX.slice(2))).toBeNull();
    expect(parseSeedText("abc")).toBeNull();
  });
});

describe("PKCS8 PEM (generated by the official cryptography library)", () => {
  beforeAll(() => {
    if (!existsSync(ENC_PEM)) throw new Error("fixture missing");
  });

  it("extracts the seed from plain PKCS8 PEM", async () => {
    const seed = await seedFromPlainPem(readFileSync(PLAIN_PEM, "utf8"));
    expect(seedToHex(seed)).toBe(SEED_HEX);
  });

  it("decrypts PBES2 encrypted PKCS8 PEM with the passphrase", async () => {
    const seed = await seedFromEncryptedPem(readFileSync(ENC_PEM, "utf8"), ENC_PASS);
    expect(seedToHex(seed)).toBe(SEED_HEX);
  });

  it("rejects a wrong passphrase on encrypted PEM", async () => {
    await expect(
      seedFromEncryptedPem(readFileSync(ENC_PEM, "utf8"), "wrong-passphrase"),
    ).rejects.toThrow(/wrong passphrase|unsupported/);
  });

  it("resolveImport handles pem-plain and returns the matching did", async () => {
    const res = await resolveImport(readFileSync(PLAIN_PEM, "utf8"));
    expect(res.did).toBe(EXPECTED_DID);
    expect(res.seed.length).toBe(32);
  });

  it("resolveImport handles pem-encrypted with passphrase", async () => {
    const res = await resolveImport(readFileSync(ENC_PEM, "utf8"), ENC_PASS);
    expect(res.did).toBe(EXPECTED_DID);
  });

  it("resolveImport requires a passphrase for encrypted PEM", async () => {
    await expect(resolveImport(readFileSync(ENC_PEM, "utf8"))).rejects.toThrow(/passphrase required/);
  });
});

describe("round-trip through our encrypted JSON", () => {
  it("import -> re-encrypt -> decrypt yields the same key", async () => {
    const seed = generateSeed();
    const pub = publicKeyFromSeed(seed);
    const did = didFromPublicKey(pub);
    const file = await encryptIdentity(seed, did, pub, "new-passphrase-12345");
    const unlocked = await decryptIdentity(file, "new-passphrase-12345");
    expect(unlocked.did).toBe(did);
    expect(seedToHex(unlocked.seed)).toBe(seedToHex(seed));
  });
});